### ISSUE TITLE
Dashboard page: UI improvements

### ISSUE THREAD

**Issue by jvdassen** [ddosgrid/ddos-visualization#50]
- consistent height of datasettiles
- Metrics visualized
- Preserve order of dashboard tiles in setups

**Comment by lucBoillat** [comment]
done until now:
- merge datasets and visualisations into single array in store
     - due to the new html structure the dataset tile and visualisation tiles do not share the same heigh anymore -> this can be fixed by using dynamic components
- metrics have been added to dataset tiles with collapsable list items, idea is to categorize metrics into certain categories like "Attack Stats" and "Network Stats". to be discussed.
- visualization buttons have also been put into an expandable list
     - curent problem: due to the way the tabs or list works in vue-material, the height of the tab/list is only as high as the content, so this interferes with animations. when a list item is expanded it takes time until the height of the container adjusts resulting in sloppy presentation.
